query Posts {
  posts(where: {_sort: "id:desc", _limit: 9}) {
    id
    updated_at
    slug
    Title
    content
    Image {
      url
    }
    categories {
      id
      Name
    }
    comments {
      Name
      Content
    }
  }
}
